general:
  announcedelay: 60
  debug: false
  defaultWorld: world
  defaultGameType: TSL
  defaultMap: Tharbad
  spawn:
    ==: Vector
    x: -165.0
    y: 98.0
    z: 1824.0
consolechat:
  prefix: '[MCMEPVP] (Chat)'
  suffix: ':'
status:
  open: 'OPEN'
  closed: 'CLOSED'
  beta: 'BETA TESTING'
lobby:
  enableAutoLobby: false
  minOnlinePlayers: 6
  startThreshHold: 0.75
  enableMapVote: true
score:
  TSL: 25
  TCQ: 50
infection:
  time: 10
  zombiehealth: 12
freeforall:
  time: 10
sql:
  user: root
  password: 
  database: minecraft
  host: localhost
  port: 3306
  playertable: pvp_players
  killtable: pvp_kills
  wintable: pvp_wins
  gametable: pvp_games
  logdelay: 2
textures:
  eriador: http://mcme.co/texturepacks/eriador/MCME-Eriador-Pack-v1.01.zip
  rohan: http://mcme.co/texturepacks/rohan/MCME-Rohan-Pack-v0.72.zip
  lothlorien: http://mcme.co/texturepacks/lothorien/MCME-Loth-Pack-v0.74.zip
maps:
- Tharbad
- Annuminas
- Aldburg
- Moria2
- Rivendell
- Test
- Ost-in-Edhil
- Fornost1
- Fornost2
- Fornost3
loot:
gametypes:
- TDM
- TSL
- TCQ
- RBR
- INF