name: ${project.artifactId}
main: co.mcme.pvp.MCMEPVP
version: ${project.version}
website: ${project.url}
softdepend: [VoxelSniper]
authors: [meggawatts, daggs]
permissions:
  mcmepvp.user:
    default: true
    children:
      mcmepvp.join: true
      mcmepvp.leave: true
      mcmepvp.shout: true
      mcmepvp.list: true
      mcmepvp.version: true
  mcmepvp.admin:
    default: op
    children:
      mcmepvp.user: true
      mcmepvp.start: true
      mcmepvp.set: true
      mcmepvp.stop: true
      mcmepvp.map: true
      mcmepvp.derp: true
      mcmepvp.gt: true
      mcmepvp.add: true
      mcmepvp.remove: true
      mcmepvp.list: true
      mcmepvp.adminchat: true
      mcmepvp.setscore: true
      mcmepvp.unlock: true
      mcmepvp.lock: true
      mcmepvp.ignorelock: true
      mcmepvp.forcejoin: true
      mcmepvp.createlootsign: true
      mcmepvp.remind: true
      mcmepvp.ignorebuildchecks: true
      mcmepvp.autorun: true
      mcmepvp.horsemode: true
  mcmepvp.version:
    default: true
  mcmepvp.join:
    default: true
  mcmepvp.leave:
    default: true
  mcmepvp.shout:
    default: true
  mcmepvp.setdebug:
    default: op
  mcmepvp.ignorebuildchecks:
    default: op  
  mcmepvp.remind:
    default: op  
  mcmepvp.createlootsign:
    default: op
  mcmepvp.forcejoin:
    default: op
  mcmepvp.setscore:
    default: op
  mcmepvp.lock:
    default: op
  mcmepvp.unlock:
    default: op
  mcmepvp.start:
    default: op
  mcmepvp.derp:
    default: op
  mcmepvp.set:
    default: op
  mcmepvp.stop:
    default: op
  mcmepvp.map:
    default: op
  mcmepvp.gt:
    default: op
  mcmepvp.adminchat:
    default: op
  mcmepvp.ignorelock:
    default: op
  mcmepvp.add:
    default: op
  mcmepvp.remove:
    default: op
  mcmepvp.list:
    default: op
  mcmepvp.horsemode:
    default: op
  mcmepvp.autorun:
    default: op
commands:
   pvp:
      description: PVP
      usage: /<command> [join|start|map|gt|set|stop|setscore|lock|unlock|forcejoin]
   shout:
      description: Shout a message to Everyone!
      usage: /<command> [msg]
   a:
      description: Chat only for Admins!
      usage: /<command> [msg]
